INSERT OR IGNORE INTO rulesets (name, schema_json, version) VALUES
  ('shadowrun',    '{"system":"shadowrun","fields":["metatype","priority","body","agility","reaction","strength","willpower","logic","intuition","charisma","edge","essence","physical_limit","mental_limit","social_limit","nuyen","karma","reputation","notoriety","notes"]}', '6e'),
  ('wfrp',         '{"system":"wfrp","fields":["species","career","career_level","ws","bs","s","t","ag","i","dex","int","wp","fel","wounds","fate","fortune","resilience","resolve","xp","ambitions","notes"]}', '4e'),
  ('starwars',     '{"system":"starwars","fields":["species","career","specialization","brawn","agility","intellect","cunning","willpower","presence","wounds_threshold","wounds_current","strain_threshold","strain_current","soak","defense_melee","defense_ranged","obligation","credits","force_rating","notes"]}', 'EotE'),
  ('l5r',          '{"system":"l5r","fields":["clan","family","school","school_rank","air","earth","fire","water","void","endurance","composure","focus","vigilance","glory","honor","status","xp","notes"]}', 'FFG5e'),
  ('theonering',   '{"system":"theonering","fields":["culture","calling","body","heart","wits","endurance","endurance_max","hope","hope_max","shadow_points","shadow_scars","valour","wisdom","standing","fellowship_score","notes"]}', '2e'),
  ('wrath_glory',  '{"system":"wrath_glory","fields":["archetype","faction","rank","strength","agility","toughness","intellect","willpower","fellowship","initiative","wounds","shock","resilience","determination","defence","resolve","conviction","wrath","glory","ruin","xp","keywords","notes"]}', 'W&G'),
  ('blades',       '{"system":"blades","fields":["playbook","heritage","background","vice","hunt","study","survey","tinker","finesse","prowl","skirmish","wreck","attune","command","consort","sway","stress","trauma","coin","stash","load","xp_insight","xp_prowess","xp_resolve","notes"]}', '1.0'),
  ('paranoia',     '{"system":"paranoia","fields":["full_name","sector","security_clearance","management_style","power_group","secret_society","violence","treachery","happiness","straight","moxie","credits","clone_number","treason_points","notes"]}', '2017');
