-- Update rulesets to typed schema format so CharacterSheetPanel can render number fields in 2-col grid
UPDATE rulesets SET schema_json = '[
  {"key":"archetype","label":"Archetype","type":"text"},
  {"key":"faction","label":"Faction","type":"text"},
  {"key":"rank","label":"Rank","type":"number"},
  {"key":"strength","label":"Strength","type":"number"},
  {"key":"agility","label":"Agility","type":"number"},
  {"key":"toughness","label":"Toughness","type":"number"},
  {"key":"intellect","label":"Intellect","type":"number"},
  {"key":"willpower","label":"Willpower","type":"number"},
  {"key":"fellowship","label":"Fellowship","type":"number"},
  {"key":"initiative","label":"Initiative","type":"number"},
  {"key":"wounds","label":"Wounds","type":"number"},
  {"key":"shock","label":"Shock","type":"number"},
  {"key":"resilience","label":"Resilience","type":"number"},
  {"key":"determination","label":"Determination","type":"number"},
  {"key":"defence","label":"Defence","type":"number"},
  {"key":"resolve","label":"Resolve","type":"number"},
  {"key":"conviction","label":"Conviction","type":"number"},
  {"key":"wrath","label":"Wrath","type":"number"},
  {"key":"glory","label":"Glory","type":"number"},
  {"key":"ruin","label":"Ruin","type":"number"},
  {"key":"xp","label":"XP","type":"number"},
  {"key":"keywords","label":"Keywords","type":"text"},
  {"key":"notes","label":"Notes","type":"textarea"}
]' WHERE name = 'wrath_glory';

UPDATE rulesets SET schema_json = '[
  {"key":"playbook","label":"Playbook","type":"text"},
  {"key":"heritage","label":"Heritage","type":"text"},
  {"key":"background","label":"Background","type":"text"},
  {"key":"vice","label":"Vice","type":"text"},
  {"key":"hunt","label":"Hunt","type":"number"},
  {"key":"study","label":"Study","type":"number"},
  {"key":"survey","label":"Survey","type":"number"},
  {"key":"tinker","label":"Tinker","type":"number"},
  {"key":"finesse","label":"Finesse","type":"number"},
  {"key":"prowl","label":"Prowl","type":"number"},
  {"key":"skirmish","label":"Skirmish","type":"number"},
  {"key":"wreck","label":"Wreck","type":"number"},
  {"key":"attune","label":"Attune","type":"number"},
  {"key":"command","label":"Command","type":"number"},
  {"key":"consort","label":"Consort","type":"number"},
  {"key":"sway","label":"Sway","type":"number"},
  {"key":"stress","label":"Stress","type":"number"},
  {"key":"trauma","label":"Trauma","type":"number"},
  {"key":"coin","label":"Coin","type":"number"},
  {"key":"stash","label":"Stash","type":"number"},
  {"key":"load","label":"Load","type":"number"},
  {"key":"xp_insight","label":"XP Insight","type":"number"},
  {"key":"xp_prowess","label":"XP Prowess","type":"number"},
  {"key":"xp_resolve","label":"XP Resolve","type":"number"},
  {"key":"notes","label":"Notes","type":"textarea"}
]' WHERE name = 'blades';

UPDATE rulesets SET schema_json = '[
  {"key":"species","label":"Species","type":"text"},
  {"key":"career","label":"Career","type":"text"},
  {"key":"career_level","label":"Career Level","type":"number"},
  {"key":"ws","label":"WS","type":"number"},
  {"key":"bs","label":"BS","type":"number"},
  {"key":"s","label":"S","type":"number"},
  {"key":"t","label":"T","type":"number"},
  {"key":"ag","label":"Ag","type":"number"},
  {"key":"i","label":"I","type":"number"},
  {"key":"dex","label":"Dex","type":"number"},
  {"key":"int","label":"Int","type":"number"},
  {"key":"wp","label":"WP","type":"number"},
  {"key":"fel","label":"Fel","type":"number"},
  {"key":"wounds","label":"Wounds","type":"number"},
  {"key":"fate","label":"Fate","type":"number"},
  {"key":"fortune","label":"Fortune","type":"number"},
  {"key":"resilience","label":"Resilience","type":"number"},
  {"key":"resolve","label":"Resolve","type":"number"},
  {"key":"xp","label":"XP","type":"number"},
  {"key":"ambitions","label":"Ambitions","type":"textarea"},
  {"key":"notes","label":"Notes","type":"textarea"}
]' WHERE name = 'wfrp';

UPDATE rulesets SET schema_json = '[
  {"key":"metatype","label":"Metatype","type":"text"},
  {"key":"priority","label":"Priority","type":"text"},
  {"key":"body","label":"Body","type":"number"},
  {"key":"agility","label":"Agility","type":"number"},
  {"key":"reaction","label":"Reaction","type":"number"},
  {"key":"strength","label":"Strength","type":"number"},
  {"key":"willpower","label":"Willpower","type":"number"},
  {"key":"logic","label":"Logic","type":"number"},
  {"key":"intuition","label":"Intuition","type":"number"},
  {"key":"charisma","label":"Charisma","type":"number"},
  {"key":"edge","label":"Edge","type":"number"},
  {"key":"essence","label":"Essence","type":"number"},
  {"key":"physical_limit","label":"Phys Limit","type":"number"},
  {"key":"mental_limit","label":"Mental Limit","type":"number"},
  {"key":"social_limit","label":"Social Limit","type":"number"},
  {"key":"nuyen","label":"Nuyen","type":"number"},
  {"key":"karma","label":"Karma","type":"number"},
  {"key":"reputation","label":"Reputation","type":"number"},
  {"key":"notoriety","label":"Notoriety","type":"number"},
  {"key":"notes","label":"Notes","type":"textarea"}
]' WHERE name = 'shadowrun';

UPDATE rulesets SET schema_json = '[
  {"key":"species","label":"Species","type":"text"},
  {"key":"career","label":"Career","type":"text"},
  {"key":"specialization","label":"Specialization","type":"text"},
  {"key":"brawn","label":"Brawn","type":"number"},
  {"key":"agility","label":"Agility","type":"number"},
  {"key":"intellect","label":"Intellect","type":"number"},
  {"key":"cunning","label":"Cunning","type":"number"},
  {"key":"willpower","label":"Willpower","type":"number"},
  {"key":"presence","label":"Presence","type":"number"},
  {"key":"wounds_threshold","label":"Wounds Max","type":"number"},
  {"key":"wounds_current","label":"Wounds","type":"number"},
  {"key":"strain_threshold","label":"Strain Max","type":"number"},
  {"key":"strain_current","label":"Strain","type":"number"},
  {"key":"soak","label":"Soak","type":"number"},
  {"key":"defense_melee","label":"Def Melee","type":"number"},
  {"key":"defense_ranged","label":"Def Ranged","type":"number"},
  {"key":"obligation","label":"Obligation","type":"number"},
  {"key":"credits","label":"Credits","type":"number"},
  {"key":"force_rating","label":"Force Rating","type":"number"},
  {"key":"notes","label":"Notes","type":"textarea"}
]' WHERE name = 'starwars';

UPDATE rulesets SET schema_json = '[
  {"key":"clan","label":"Clan","type":"text"},
  {"key":"family","label":"Family","type":"text"},
  {"key":"school","label":"School","type":"text"},
  {"key":"school_rank","label":"School Rank","type":"number"},
  {"key":"air","label":"Air","type":"number"},
  {"key":"earth","label":"Earth","type":"number"},
  {"key":"fire","label":"Fire","type":"number"},
  {"key":"water","label":"Water","type":"number"},
  {"key":"void","label":"Void","type":"number"},
  {"key":"endurance","label":"Endurance","type":"number"},
  {"key":"composure","label":"Composure","type":"number"},
  {"key":"focus","label":"Focus","type":"number"},
  {"key":"vigilance","label":"Vigilance","type":"number"},
  {"key":"glory","label":"Glory","type":"number"},
  {"key":"honor","label":"Honor","type":"number"},
  {"key":"status","label":"Status","type":"number"},
  {"key":"xp","label":"XP","type":"number"},
  {"key":"notes","label":"Notes","type":"textarea"}
]' WHERE name = 'l5r';

UPDATE rulesets SET schema_json = '[
  {"key":"culture","label":"Culture","type":"text"},
  {"key":"calling","label":"Calling","type":"text"},
  {"key":"body","label":"Body","type":"number"},
  {"key":"heart","label":"Heart","type":"number"},
  {"key":"wits","label":"Wits","type":"number"},
  {"key":"endurance","label":"Endurance","type":"number"},
  {"key":"endurance_max","label":"Endurance Max","type":"number"},
  {"key":"hope","label":"Hope","type":"number"},
  {"key":"hope_max","label":"Hope Max","type":"number"},
  {"key":"shadow_points","label":"Shadow Pts","type":"number"},
  {"key":"shadow_scars","label":"Shadow Scars","type":"number"},
  {"key":"valour","label":"Valour","type":"number"},
  {"key":"wisdom","label":"Wisdom","type":"number"},
  {"key":"standing","label":"Standing","type":"number"},
  {"key":"fellowship_score","label":"Fellowship","type":"number"},
  {"key":"notes","label":"Notes","type":"textarea"}
]' WHERE name = 'theonering';

UPDATE rulesets SET schema_json = '[
  {"key":"full_name","label":"Full Name","type":"text"},
  {"key":"sector","label":"Sector","type":"text"},
  {"key":"security_clearance","label":"Clearance","type":"text"},
  {"key":"management_style","label":"Mgmt Style","type":"text"},
  {"key":"power_group","label":"Power Group","type":"text"},
  {"key":"secret_society","label":"Secret Society","type":"text"},
  {"key":"violence","label":"Violence","type":"number"},
  {"key":"treachery","label":"Treachery","type":"number"},
  {"key":"happiness","label":"Happiness","type":"number"},
  {"key":"straight","label":"Straight","type":"number"},
  {"key":"moxie","label":"Moxie","type":"number"},
  {"key":"credits","label":"Credits","type":"number"},
  {"key":"clone_number","label":"Clone #","type":"number"},
  {"key":"treason_points","label":"Treason Pts","type":"number"},
  {"key":"notes","label":"Notes","type":"textarea"}
]' WHERE name = 'paranoia';
