// Wrath & Glory talent and archetype ability descriptions.
// Used by the Talents & Powers overlay panel.

export const wgTalentDescriptions: Record<string, string> = {
  // ── Archetype Starting Abilities ──────────────────────────────────────────
  "Fiery Invective": "You can make a Fear-equivalent attack using your voice and presence. On a successful Intimidation (Wil) test, the target suffers the Frightened condition.",
  "Psyker": "You have the ability to channel the power of the Warp. You may learn and use psychic powers appropriate to your discipline.",
  "Corruption": "Your soul bears the taint of Chaos. You may gain Corruption points and access to forbidden knowledge, but risk mutation and madness.",
  "Dark Pact": "You have made a pact with dark powers. Gain access to forbidden abilities, but the dark powers may call in their debt at any time.",
  "Enemy Within": "A daemon or warp entity is bound within you. You can call upon its power, but it seeks to control or destroy you.",
  "Mechadendrite (Utility)": "You have a utility mechadendrite implanted that can perform basic technical tasks and carries a suite of tools.",
  "Mechadendrite (Weapon)": "You have a weapon mechadendrite that functions as an additional limb capable of wielding a weapon in combat.",
  "Blessed by the Emperor": "The Emperor's light protects you. You may re-roll one die on any test to resist Corruption, Fear, or psychic effects once per scene.",
  "Oath of Moment": "You have sworn a personal oath to uphold a specific ideal or destroy a particular enemy. While acting in its service, gain +1d to relevant tests.",
  "Unnatural Senses": "You perceive the world through non-standard senses — Warp-sight, auspex integration, or other means. You cannot be fully blinded.",
  "Weapon Expertise": "Extensive training grants you +1 die on all attack tests with your chosen weapon type.",
  "Fearless": "You are immune to the Frightened condition and automatically pass Fear tests.",
  "Nerves of Steel": "When you fail a Willpower test, you may immediately re-roll it, keeping the second result.",
  "Born Warrior": "You were born to fight. When making a melee attack, you may re-roll one die result of 1.",
  "Chosen of the Machine God": "The Omnissiah watches over you. Once per session you may treat a failed Tech-Use test as a success.",
  "Voice of Command": "Your orders carry authority. Allies within earshot who hear your command may re-roll one failed Leadership test result per turn.",

  // ── Weapon Training ───────────────────────────────────────────────────────
  "Weapon Training (Bolt)":             "You are trained in the use of bolt weapons (boltguns, bolt pistols, storm bolters). You do not suffer penalties for Unskilled use.",
  "Weapon Training (Chain)":            "You are trained in chain weapons (chainswords, chain axes). You do not suffer penalties for Unskilled use.",
  "Weapon Training (Flame)":            "You are trained in flame weapons (flamers, hand flamers). You do not suffer penalties for Unskilled use.",
  "Weapon Training (Las)":              "You are trained in las weapons (lasguns, laspistols, lascannons). You do not suffer penalties for Unskilled use.",
  "Weapon Training (Shock)":            "You are trained in shock weapons (shock mauls, power mauls). You do not suffer penalties for Unskilled use.",
  "Weapon Training (Solid Projectile)": "You are trained in solid projectile weapons (autoguns, autopistols). You do not suffer penalties for Unskilled use.",
  "Weapon Training (Melta)":            "You are trained in melta weapons (meltaguns, melta pistols). You do not suffer penalties for Unskilled use.",
  "Weapon Training (Plasma)":           "You are trained in plasma weapons (plasma guns, plasma pistols). You do not suffer penalties for Unskilled use.",
  "Weapon Training (Power)":            "You are trained in power weapons (power swords, power fists). You do not suffer penalties for Unskilled use.",
  "Weapon Training (Launcher)":         "You are trained in launcher weapons (grenade launchers, missile launchers). You do not suffer penalties for Unskilled use.",
  "Weapon Training (Primitive)":        "You are trained in primitive weapons (bows, spears, clubs). You do not suffer penalties for Unskilled use.",

  // ── Armour Proficiency ────────────────────────────────────────────────────
  "Armour Proficiency (Flak)":     "You can wear flak armour without penalty. Flak armour provides Resilience +2.",
  "Armour Proficiency (Mesh)":     "You can wear mesh armour without penalty. Mesh armour provides Resilience +3 and is concealable.",
  "Armour Proficiency (Carapace)": "You can wear carapace armour without penalty. Carapace armour provides Resilience +4.",
  "Armour Proficiency (Power)":    "You can wear power armour without penalty. Power armour provides Resilience +5 and enhances Strength.",

  // ── Forbidden Lore ────────────────────────────────────────────────────────
  "Forbidden Lore (Daemonology)": "You have studied the nature of daemons. Add +1d to Scholar tests involving daemons, the Warp, and summoning rituals.",
  "Forbidden Lore (Heresy)":      "You know the ways of heretics and traitors. Add +1d to Scholar tests about heretical cults, chaos worship, and sedition.",
  "Forbidden Lore (Mutants)":     "You understand mutation and its causes. Add +1d to Scholar tests related to mutants and the causes of physical corruption.",
  "Forbidden Lore (Psykers)":     "You have studied psykers and their abilities. Add +1d to Scholar tests about psykers, sanctioning, and psychic phenomena.",
  "Forbidden Lore (The Warp)":    "You understand the Warp's nature. Add +1d to Scholar tests about the immaterium, warp travel, and warp entities.",
  "Forbidden Lore (Xenos)":       "You have studied alien races. Add +1d to Scholar tests about xenos species, their cultures, and their technology.",

  // ── Peer ──────────────────────────────────────────────────────────────────
  "Peer (Adeptus Mechanicus)": "You have contacts within the Adeptus Mechanicus. Gain +1d on Interaction tests with its members.",
  "Peer (Adeptus Ministorum)": "You have contacts within the Adeptus Ministorum. Gain +1d on Interaction tests with priests and confessors.",
  "Peer (Aeldari)":            "You have contacts among the Aeldari. Gain +1d on Interaction tests with Aeldari characters.",
  "Peer (Astra Militarum)":    "You have contacts within the Imperial Guard. Gain +1d on Interaction tests with soldiers and officers.",
  "Peer (Criminal)":           "You know your way around criminal organisations. Gain +1d on Interaction tests with gangers, smugglers, and crime lords.",
  "Peer (Inquisition)":        "You have contacts within the Inquisition. Gain +1d on Interaction tests with Inquisitors and their agents.",
  "Peer (Orks)":               "Somehow you get along with Orks. Gain +1d on Interaction tests when dealing with greenskin clans.",
  "Peer (Rogue Traders)":      "You have contacts among Rogue Traders. Gain +1d on Interaction tests with Rogue Trader crews and dynasties.",
  "Peer (Underworld)":         "You have contacts in the criminal underworld. Gain +1d on Interaction tests with black market traders and underground figures.",

  // ── Resistance / Hatred ───────────────────────────────────────────────────
  "Resistance (Fear)":           "Your nerves are hardened. Add +1d to all tests to resist Fear and the Frightened condition.",
  "Resistance (Poison)":         "Your body resists toxins. Add +1d to all tests to resist poison effects and reduce their duration.",
  "Resistance (Psychic Powers)": "Your mind resists psychic intrusion. Add +1d to all tests to resist psychic effects and warp phenomena.",
  "Hatred (Chaos)":              "Your hatred of Chaos fuels your strikes. Add +1d to Weapon Skill and Ballistic Skill tests against Chaos-aligned targets.",
  "Hatred (Daemons)":            "You burn with hatred for daemons. Add +1d to attack tests against daemonic targets, and deal +1 damage on hits.",
  "Hatred (Greenskins)":         "Your loathing for Orks and their kin is total. Add +1d to Weapon Skill and Ballistic Skill tests against greenskins.",
  "Hatred (Heretics)":           "You fight with righteous fury against heretics. Add +1d to attack tests against heretics and traitors.",
  "Hatred (Xenos)":              "You despise alien life in all forms. Add +1d to attack tests against xenos targets.",

  // ── Combat ────────────────────────────────────────────────────────────────
  "Acute Senses":        "Your senses are sharper than normal. Gain +1d to Awareness tests and you are not surprised unless caught completely unaware.",
  "Ambidextrous":        "You fight equally well with either hand. Ignore all penalties for off-hand weapon use.",
  "Blind Fighting":      "You can fight effectively without sight. Ignore all penalties for fighting in darkness or while blinded.",
  "Blood of Heroes":     "When you are reduced to 0 Wounds but not killed, make a Toughness test to stay standing with 1 Wound instead.",
  "Brutal Charge":       "Your charges are devastating. When you charge, deal +2 damage on your first hit.",
  "Bulging Biceps":      "Your powerful arms let you wield heavy weapons one-handed without bracing, and you ignore the Unwieldy trait penalty.",
  "Careful Aim":         "When you spend a full action aiming, you add +1d to your next attack instead of the usual bonus.",
  "Catfall":             "You land on your feet. Reduce falling damage by half, and never count as prone after a fall.",
  "Cold-Blooded":        "You remain calm under extreme stress. Gain +1d to Willpower tests against Fear and Pinning.",
  "Combat Formation":    "You and your allies fight as a unit. When adjacent to an ally, both of you gain +1 Defence.",
  "Combat Master":       "Your battlefield awareness is supreme. Enemies attacking you in melee never gain bonuses for outnumbering you.",
  "Combat Sense":        "Your instincts warn you of danger. You are never surprised and always act in the first round of combat.",
  "Counter Attack":      "When an enemy misses you in melee, you may immediately make one free attack against them.",
  "Crushing Blow":       "Your melee strikes are bone-shattering. Add your Strength bonus to melee damage once per turn.",
  "Dead Eye Shot":       "You can target specific locations with precision. Called shots cost 1 fewer Action Point for you.",
  "Defensive Fighting":  "You can fight on the defensive. As a free action each turn, add +2 Defence but reduce your attack dice pool by 1.",
  "Deflect":             "You can deflect incoming attacks with your weapon or shield, reducing damage by your Agility bonus once per round.",
  "Die Hard":            "You cling to life. When you would gain a Critical Wound, roll 1d6; on a 6, ignore it.",
  "Double Team":         "When you and an ally attack the same target in the same turn, both gain +1d on those attacks.",
  "Dual Strike":         "You can strike with both weapons in a single action. Make two attacks as one action; both are at −1d.",
  "Expert at Violence":  "Your experience in battle is vast. Once per scene, re-roll any one failed attack test.",
  "Eye of Vengeance":    "When a comrade is wounded, you fight harder. Gain +1d on all attack tests for the rest of the scene.",
  "Feel No Pain":        "You push through wounds that would cripple others. Once per round, ignore the effects of one wound.",
  "Frenzy":              "You can work yourself into a battle frenzy. While frenzied gain +2 Strength, +2 Toughness, −2 Defence.",
  "Hard Target":         "You move unpredictably in combat. When you move before being attacked, enemies suffer −1d on ranged attacks against you.",
  "Heavy Hitter":        "Your melee blows are crushing. Increase melee damage by 1 against targets with Resilience lower than your Strength.",
  "Hip Shooting":        "You can fire on the move without penalty. Move and shoot in the same turn with no penalty to your attack roll.",
  "Hotshot":             "Your shots hit with spectacular force. Once per scene, double the damage of a single successful ranged attack.",
  "Iron Jaw":            "Your jaw and skull are exceptionally tough. Ignore Stagger effects; you cannot be knocked out by physical impacts.",
  "Iron Will":           "Your mental fortitude is immense. Gain +2 to all Willpower-based tests against psychic attacks and warp effects.",
  "Lay Low":             "You know how to stay out of sight. Gain +1d on all Stealth tests and you can hide even when observed if you move carefully.",
  "Lightning Attack":    "Your attacks come in a blur. Make two melee attacks per action once per round, both at full dice pool.",
  "Marksman":            "You are a crack shot. Ignore range penalties on ranged attacks, and ignore cover that provides less than +2 Defence.",
  "Master Orator":       "Your words move crowds and leaders alike. Gain +2d to all Persuasion and Leadership tests when addressing groups.",
  "Mechadendrite Use (Utility)": "You have a utility mechadendrite you can use to perform Tech-Use tests without hands. It also carries basic tools.",
  "Mechadendrite Use (Weapon)":  "You can use a weapon mechadendrite as an extra limb, making one free attack per round with it.",
  "Mighty Blow":         "Your strikes are legendary. Once per combat, make an attack that deals maximum damage automatically.",
  "Nimble":              "You move with exceptional grace. Gain +2 Agility for determining Initiative and Dodge.",
  "Nowhere to Hide":     "Your attacks find their mark regardless of cover. Targets in cover lose their Defence bonus against your attacks.",
  "Overwhelming Blow":   "Your attacks carry tremendous force. On a hit, the target must pass a Toughness test or be knocked prone.",
  "Pack Tactics":        "You fight best alongside allies. When at least two allies are adjacent to your target, gain +1d on attacks.",
  "Power Behind the Blow": "You put your full weight into every strike. Add your Toughness bonus to melee damage.",
  "Practiced Aim":       "You can take time to aim even in a crisis. Spend 1 Action Point to aim for the same bonus as a full-action aim.",
  "Preternatural Speed": "Your reflexes defy human limits. Always act first in Initiative order and add +3 to your Initiative roll.",
  "Quick Draw":          "You can draw and fire in a single motion. Drawing a weapon no longer costs an Action Point.",
  "Rapid Fire":          "You unleash a storm of shots. When firing a semi-auto weapon, make one extra attack at −1d.",
  "Rapid Reload":        "You reload weapons with practiced speed. Reloading costs 1 fewer Action Point (minimum 1).",
  "Reckless Charge":     "You charge without regard for your own safety. Your charge attacks gain +2 damage but leave you at −2 Defence until your next turn.",
  "Savant":              "Your mind absorbs information rapidly. Gain +1d on all Scholar and Lore tests when working from books or data-slates.",
  "Shield Wall":         "You can interpose your shield to protect nearby allies. Adjacent allies may use your shield's Defence bonus.",
  "Sidestep":            "You move out of the way of incoming attacks. Once per round, dodge an attack without spending an Action Point.",
  "Sixth Sense":         "An uncanny awareness keeps you safe. You cannot be ambushed and are always considered alert even when sleeping.",
  "Skirmisher":          "You excel at mobile combat. You can move and make a ranged attack as a single action without penalty.",
  "Sprint":              "You can move at tremendous speed. When you run, double your movement rate for that turn.",
  "Step Aside":          "Your footwork lets you avoid attacks effortlessly. Gain +1d on Dodge tests when you have not moved this turn.",
  "Storm of Blows":      "Your melee attacks come in rapid succession. Make three melee attacks as a single action, each at −1d.",
  "Sure Strike":         "You land your blows precisely. Reduce the target's Defence by 1 when calculating whether your melee attacks hit.",
  "Swift Attack":        "You attack faster than the eye can follow. Make two melee attacks per round without penalty.",
  "Takedown":            "You can take enemies out of action non-lethally. A successful melee hit may render the target Stunned instead of dealing wounds.",
  "Tech-Use":            "You understand technology beyond the ordinary person. Gain +1d to all Tech-Use tests and can repair devices others cannot.",
  "True Grit":           "You endure injuries that would fell lesser warriors. Reduce the severity of all Critical Wounds by 1.",
  "Unarmed Warrior":     "Your bare hands are lethal weapons. Unarmed attacks deal 1d6+Str damage and you are not treated as an Unskilled combatant.",
  "Unshakeable Faith":   "Your belief in the Emperor is a fortress. Gain +2d to Willpower tests against Fear and Corruption.",
  "Wall of Steel":       "Your blocks and parries are relentless. Once per round, automatically cancel one melee hit without a roll.",
  "Whirlwind of Death":  "You spin through enemies in a deadly arc. Once per combat, attack all adjacent enemies simultaneously.",
  "Demolition Expert":   "You understand explosives instinctively. Gain +2d on all tests to set or defuse explosives; your bombs deal +1 damage.",
  "Disturbing Voice":    "Your voice unsettles all who hear it. Gain +1d on Intimidation tests; civilians may flee at your approach.",
  "Never Say Die":       "You refuse to go down. Once per combat, when reduced to 0 Wounds, remain conscious on 1 Wound for one more round.",
  "Paranoia":            "You are always watching for threats. You can never be surprised and gain +1d on Awareness tests for potential danger.",
  "Banishment":          "You can drive daemons back to the Warp. Make a Willpower test to banish a daemon; success sends it back without destroying it.",
  "Exceptional Leader":  "Your command presence is extraordinary. Once per scene, grant all allies in earshot a free re-roll on one failed test.",
  "Rite of Awe":         "Your bearing inspires terror in enemies. Once per combat, force all visible enemies to pass a Willpower test or become Frightened.",
  "Weapon Mastery":      "You have achieved mastery with your chosen weapon. Gain +1d on all attacks and deal +2 damage with your chosen weapon type.",
  "Will Not Die":        "You cannot be stopped by conventional wounds. Once per session, ignore death — survive what should kill you on a Toughness test.",
  "Warp Conduit":        "The Warp flows through you more freely than most. Add +2 to your Psychic Mastery and reduce the Warp Charge cost of all powers by 1.",
  "Untouchable Talent":  "The Warp cannot touch you at all. You are immune to all psychic powers, whether beneficial or harmful.",
}

/** Returns a description for a talent/ability name, or empty string if unknown. */
export function wgTalentDescription(name: string): string {
  return wgTalentDescriptions[name] ?? ''
}
